name: Unittests & Auto-publish

# Allow to trigger the workflow manually (e.g. when deps changes)
on: [push, workflow_dispatch]

jobs:
  pytest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    # Install deps
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        # Uncomment to cache of pip dependencies (if tests too slow)
        # cache: pip
        # cache-dependency-path: '**/pyproject.toml'

    - run: pip --version
    - run: pip install -e .[dev]
    - run: pip freeze

    # Run tests (in parallel)
    - name: Run core tests
      # Skip dataset tests that require downloading and preprocessing data.
      run: pytest -vv -n auto -k 'not test_create_datasets and not test_train_and_evaluate_mock_qm9'
